# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Jonathan Turner"

# URL
baseurl:            "" #For Root Domain
permalink:          /:year/:month/:title.html

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Navigation
nav:
  - name:           "About"
    href:           "//jonathanturner.org/about"
  - name:           "RSS"
    href:           "//jonathanturner.org/feed.xml"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
